export const headers = [
  "Company / Issue date",
  "Issue size",
  "Price range",
  "Min invest/qty",
];

export const ipoData = [
  {
    id: 1001,
    ipoName: "GO AIR",
    fullName: "GO AIR Private Limited",
    img: "/logos/go_air.jpeg",
    date: "4th - 7th Oct 2022",
    size: "₹3600 Crores",
    range: "₹50 - 60",
    minInvest: "₹50,000",
    lotSize: "100 Shares/5 Lots",
    listOn: "15 Dec 2022",
    listPrice: "₹150",
    listingGain: {
      value: "₹10",
      profit: null,
      loss: "10.02%",
    },
  },
  {
    id: 1002,
    ipoName: "BAJAJ ENERGY",
    fullName: "BAJAJ Private Limited",
    img: "/logos/bajaj_group.jpg",
    date: "4th - 7th Oct 2022",
    size: "₹3600 Crores",
    range: "₹50 - 60",
    minInvest: "₹50,000",
    lotSize: "100 Shares/5 Lots",
    listOn: "15 Dec 2022",
    listPrice: "₹150",
    listingGain: {
      value: "₹10",
      profit: "5.45%",
      loss: null,
    },
  },
  {
    id: 1003,
    ipoName: "OYO",
    img: "/logos/oyo.png",
    fullName: "OYO Private Limited",
    date: "To be announced",
    size: "₹3600 Crores",
    range: "₹50 - 60",
    minInvest: "₹50,000",
    lotSize: "100 Shares/5 Lots",
    listOn: "15 Dec 2022",
    listPrice: "₹150",
    listingGain: {
      value: "₹10",
      profit: null,
      loss: "41.08%",
    },
  },
];
